# Generated by Django 2.0.3 on 2018-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30, unique=True)),
                ('message', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=30)),
                ('mobile_no', models.TextField(max_length=10)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
